endOfLine: "lf"

overrides:
  - files: "*.md"
    options:
      embeddedLanguageFormatting: "auto"
      printWidth: 120
      proseWrap: "never"
      singleQuote: false
      tabWidth: 2
      useTabs: false
