endOfLine: "lf"

overrides:
  - files: "*.md"
    options:
      embeddedLanguageFormatting: "auto"
      markdownLineBreaks: true
      printWidth: 80
      proseWrap: "preserve"
      singleQuote: false
      tabWidth: 2
      useTabs: false
