# ~/.config/starship.toml
# https://starship.rs/config/

# Colors
#   black
#   blue
#   brightBlack
#   brightBlue
#   brightCyan
#   brightGreen
#   brightPurple
#   brightRed
#   brightWhite
#   brightYellow
#   cyan
#   foreground
#   green
#   purple
#   red
#   white
#   yellow

command_timeout = 60000

add_newline = false

[os]
format = '[$symbol](bold cyan) '
disabled = false

[os.symbols]
Windows = ''
Ubuntu = ''
Macos = '󰀵'

[username]
disabled = false
style_user = 'green bold'
style_root = 'red bold'
format = '[$user]($style) '
show_always = true

[hostname]
disabled = false
ssh_only = false
ssh_symbol = '󰖟 '
style = 'bold yellow'
format = 'on [$ssh_symbol$hostname]($style) '

[directory]
disabled = false
style = 'blue'
truncate_to_repo = false
truncation_length = 0

[golang]
disabled = false
symbol = ' '

[python]
disabled = false
symbol = ' '

[git_metrics]
disabled = false

[git_branch]
disabled = false
symbol = ' '

[git_commit]
disabled = false
tag_symbol = ' '

[git_status]
disabled = false
# conflicted = ''
# ahead = ''
# behind = ''
# diverged = ''
# up_to_date = ''
# untracked = ''
# stashed = ''
# modified = ''
# staged = ''
# renamed = ''
# deleted = ''
# typechanged = ''

[gcloud]
disabled = true
