# NOTE: The test follows the current Fedora KDE release.
# hadolint ignore=DL3007
FROM fedora:latest

# NOTE: The setup scripts install current package versions.
# hadolint ignore=DL3041
RUN dnf install --assumeyes sudo plasma-workspace \
  && useradd --create-home --shell /bin/bash --uid 10001 tester \
  && echo 'tester ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/tester \
  && chmod 0440 /etc/sudoers.d/tester \
  && dnf clean all

COPY . /opt/dotfiles

RUN mkdir -p /home/tester/.cache/mise /home/tester/.local/share/mise \
  && chown -R tester:tester /opt/dotfiles /home/tester/.cache /home/tester/.local

USER 10001

WORKDIR /home/tester
